---
language: ruby
services:
    - docker
branches:
    only:
        - master

env:
   global:
    - DEST_ID=core
    - NSVER=7
    - DOCKER_IMAGE=nethserver/makerpms:devtoolset${NSVER}
    - >
      EVARS="
      -e DEST_ID
      -e TRAVIS_BRANCH
      -e TRAVIS_BUILD_ID
      -e TRAVIS_PULL_REQUEST_BRANCH
      -e TRAVIS_PULL_REQUEST
      -e TRAVIS_REPO_SLUG
      -e TRAVIS_TAG
      -e NSVER
      -e VERSIONS_PACK
      -e STAGES_PACK
      -e ENDPOINTS_PACK
      -e YUM_ARGS
      "

script: |
        if ! git describe --tags --exact-match --match "[0-9]*" --abbrev=7 HEAD &>/dev/null; then
          echo "[NOTICE] No tag found. libasan compilation is enabled."
          DEV_RELEASE=1
        fi
        set -e -x
        docker run -ti \
          --cap-add SYS_PTRACE \
          --name makerpms ${EVARS} \
          --hostname "b${TRAVIS_BUILD_NUMBER}.nethserver.org" \
          --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} \
          scl enable devtoolset-9 -- makerpms-travis sofia-sip.spec ${DEV_RELEASE:+-D 'dbgflags -O0 -fno-omit-frame-pointer -g3 -ggdb3 -fsanitize=address'}
        docker cp makerpms:/srv/makerpms/rpmbuild rpmbuild
        docker commit makerpms nethserver/build
        docker run -ti ${EVARS} \
          -e SECRET \
          -e SECRET_URL \
          -e AUTOBUILD_SECRET \
          -e AUTOBUILD_SECRET_URL \
          nethserver/build uploadrpms-travis
        set +x
